Repository sabeegrewal/bills-sonoma, pull requests merged in 2018-07, with the labels that each got.

#33 Update README.md
  README.md
Labels: :rocket: enhancement

#32 adding social media links
  css/style.css
  img/social_media/bandcamp-32.png
  img/social_media/bandcamp.svg
  img/social_media/facebook.svg
  img/social_media/google-plus.svg
  img/social_media/instagram.svg
  img/social_media/reddit.svg
  img/social_media/soundcloud.svg
  img/social_media/spotify.svg
  img/social_media/twitter.svg
  img/social_media/wikipedia.svg
  img/social_media/youtube.svg
  index.html
Labels: :b: bills, :rocket: enhancement

#39 Update mattt.md
  mattt.md
Labels: :b: bills

#41 addd baggg to mattt favicon
  img/bag.png
  mattt.html
  mattt.md
Labels: :m: mattt, :rocket: enhancement
